version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules/*

  lint-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  build-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn build

  deploy-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:b0:1a:52:03:cc:73:9b:d7:6a:dd:a7:1b:31:39:a9"
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: yarn deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job:
          filters:
            tags:
              only: /.*/
      - build-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - lint-job:
          requires:
            - install-job
          filters:
            tags:
              only: /.*/
      - deploy-job:
          requires:
            - lint-job
            - build-job
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
